class UnavailableEndpointError(Exception):
    """Исключение при неудачной попытке подключения к эндпойнту."""
